// MYTHRIL TIDE - sprites.js : all SNES-style pixel art, generated in code
'use strict';

const SPR = {
  _cache: new Map(),

  // ============ BAKED ATLAS (assets/ generated by dev/bake.js) ============
  atlas: null, imgShips: null, imgSprites: null, imgBg: {}, imgParchment: null,
  initAtlas() {
    if (typeof window === 'undefined' || !window.ATLAS) return;
    this.atlas = window.ATLAS;
    const mk = src => { const im = new Image(); im.src = src; return im; };
    this.imgShips = mk('assets/atlas_ships.png');
    this.imgSprites = mk('assets/atlas_sprites.png');
    this.imgBg = { day: mk('assets/bg_day.png'), storm: mk('assets/bg_storm.png'), fog: mk('assets/bg_fog.png') };
    this.imgParchment = mk('assets/parchment.png');
    // baked ship margins (art px -> logical px)
    this.SHIP_MX = this.atlas.shipMargins.MXL / 2;
    this.SHIP_MY = this.atlas.shipMargins.MYT / 2;
  },
  _frame(name) {
    if (!this.atlas) return null;
    if (this.atlas.ships[name]) return { img: this.imgShips, f: this.atlas.ships[name] };
    if (this.atlas.sprites[name]) return { img: this.imgSprites, f: this.atlas.sprites[name] };
    return null;
  },
  hasFrame(name) {
    const fr = this._frame(name);
    return !!(fr && fr.img.complete && fr.img.naturalWidth > 0);
  },
  // draw a baked frame at logical size (assets are 2x density); optional scale multiplier
  drawFrame(ctx, name, x, y, flip, scale) {
    const fr = this._frame(name);
    if (!fr || !fr.img.complete || !fr.img.naturalWidth) return false;
    const f = fr.f;
    const dw = (f.w / 2) * (scale || 1), dh = (f.h / 2) * (scale || 1);
    if (!flip) {
      ctx.drawImage(fr.img, f.x, f.y, f.w, f.h, Math.round(x), Math.round(y), dw, dh);
    } else {
      ctx.save();
      ctx.translate(Math.round(x) + dw, Math.round(y));
      ctx.scale(-1, 1);
      ctx.drawImage(fr.img, f.x, f.y, f.w, f.h, 0, 0, dw, dh);
      ctx.restore();
    }
    return true;
  },
  frameSize(name) {
    const fr = this._frame(name);
    return fr ? { w: fr.f.w / 2, h: fr.f.h / 2 } : null;
  },
  bgImage(kind) {
    const im = this.imgBg[kind] || this.imgBg.day;
    return im && im.complete && im.naturalWidth ? im : null;
  },

  // ============ USER-GENERATED AI ART (assets/art via dev/import_art.js) ============
  _art: {},
  _crewAnchor: {},  // 'crew_<race>_<pose>' -> {ax,ay,w,h} foot/contact anchor
  initArt() {
    if (typeof window === 'undefined') return;
    for (const [key, meta] of Object.entries((window.ART && window.ART.ships) || {})) {
      const im = new Image(); im.src = 'assets/' + meta.file;
      this._art[key] = { img: im, meta };
    }
    for (const [key, file] of Object.entries((window.ART && window.ART.images) || {})) {
      const im = new Image(); im.src = 'assets/' + file;
      this._art[key] = { img: im, meta: null };
    }
    // HD-2D crew pose frames (assets/crew_anim_manifest.js)
    for (const [race, poses] of Object.entries(window.CREW_ART || {})) {
      for (const [pose, m] of Object.entries(poses)) {
        const k = 'crew_' + race + '_' + pose;
        const im = new Image(); im.src = 'assets/' + m.file;
        this._art[k] = { img: im, meta: null };
        this._crewAnchor[k] = m;
      }
    }
  },
  artEntry(name) {
    const e = this._art[name];
    return e && e.img.complete && e.img.naturalWidth ? e : null;
  },
  artShip(layout, style) {
    return this.artEntry('ship_' + layout + '_' + style) || this.artEntry('ship_' + layout);
  },
  // purchased/crafted crew sprites at 2x density, anchored by feet to the room slot.
  // slotX/slotY = the 12x14 crew slot; sprite can be larger (silhouettes, hats, tails).
  drawCrewArt(ctx, race, frameIdx, flip, slotX, slotY) {
    const e = this.artEntry('crew_' + race + '_' + frameIdx);
    if (!e) return false;
    const lw = e.img.naturalWidth / 2, lh = e.img.naturalHeight / 2;
    const dx = Math.round(slotX + 6 - lw / 2);
    const dy = Math.round(slotY + 14 - lh);
    if (!flip) {
      ctx.drawImage(e.img, dx, dy, lw, lh);
    } else {
      ctx.save();
      ctx.translate(dx + lw, dy);
      ctx.scale(-1, 1);
      ctx.drawImage(e.img, 0, 0, lw, lh);
      ctx.restore();
    }
    return true;
  },

  // HD-2D pose frame: draw crew_<race>_<poseKey> at logical height targetH,
  // with its foot/contact anchor placed at (footX, footY). Returns false if the
  // pose art is absent so the caller can fall back to the legacy 2-frame sprite.
  // stable per-race reference height = the race's IDLE frame, cached. Poses are scaled by THIS
  // (a constant per race), not by each frame's own height — so a SHORT pose (a crouched repair/
  // operate) renders shorter, instead of being stretched up to full standing height (which
  // inflated its width and made the sailor look huge while repairing). The human video kit shares
  // one canvas height, so ref == every frame's height and nothing changes for it.
  _crewRefH(race) {
    if (!this._refH) this._refH = {};
    if (this._refH[race]) return this._refH[race];
    for (const key of ['idle_side1', 'idle_side', 'walk1', 'idle_front']) {
      const e = this.artEntry('crew_' + race + '_' + key);
      if (e) { this._refH[race] = e.img.naturalHeight; return this._refH[race]; }
    }
    return 0; // idle not decoded yet -> caller falls back to per-frame height this frame
  },
  drawCrewPose(ctx, race, poseKey, flip, footX, footY, targetH) {
    let k = 'crew_' + race + '_' + poseKey;
    let e = this.artEntry(k);
    // The requested pose PNG may not be decoded yet (art loads async at boot). Rather than
    // snap this sailor down to the small LEGACY sprite for a frame, substitute any pose of the
    // same race that HAS loaded — so a kitted race always renders at the HD size/style, and
    // never visibly flickers between the big new art and the small old art while loading.
    if (!e && window.CREW_ART && window.CREW_ART[race]) {
      const poses = window.CREW_ART[race];
      const order = ['idle_side', 'idle_front', 'operate', 'walk1', 'attack1'];
      for (const alt of order) { if (poses[alt]) { const ae = this.artEntry('crew_' + race + '_' + alt); if (ae) { e = ae; k = 'crew_' + race + '_' + alt; break; } } }
      if (!e) for (const alt of Object.keys(poses)) { const ae = this.artEntry('crew_' + race + '_' + alt); if (ae) { e = ae; k = 'crew_' + race + '_' + alt; break; } }
    }
    if (!e) return false; // no pose for this race has loaded at all -> legacy fallback
    const a = this._crewAnchor[k] || {};
    const nW = e.img.naturalWidth, nH = e.img.naturalHeight;
    const ref = this._crewRefH(race) || nH;   // scale by the race's idle height, not this frame's
    let scale = (targetH || ref) / ref;
    // anti-flicker: legacy kits (and a few old single poses) are cropped at varying canvas
    // heights, so an animation cycling them would flash sizes frame-to-frame. Clamp each
    // frame's rendered height to a tight band around the target so it can't visibly jump.
    const tH = targetH || ref, hh = nH * scale;
    if (hh > tH * 1.16) scale = (tH * 1.16) / nH;
    else if (hh < tH * 0.86) scale = (tH * 0.86) / nH;
    const w = nW * scale, h = nH * scale;
    const ax = (a.ax != null ? a.ax : nW / 2) * scale;
    const ay = (a.ay != null ? a.ay : nH) * scale;
    const dy = Math.round(footY - ay);
    if (!flip) {
      ctx.drawImage(e.img, Math.round(footX - ax), dy, w, h);
    } else {
      const dxf = footX - (w - ax);
      ctx.save();
      ctx.translate(Math.round(dxf + w), dy);
      ctx.scale(-1, 1);
      ctx.drawImage(e.img, 0, 0, w, h);
      ctx.restore();
    }
    return true;
  },

  // small crew icon for HUD/shop/refit lists: the hi-res PORTRAIT bust (crisp, matches the
  // crew rail), fit to the cell. Falls back to the HD pose art, then the legacy sprite.
  drawCrewIcon(ctx, race, x, y, box) {
    box = box || 12;
    const pr = this.artEntry('portrait_' + (race === 'armada' ? 'admiral' : race === 'ghost' ? 'siren' : race));
    if (pr) {
      const s = box + 5;                                  // a touch larger than the cell so the face fills it
      ctx.drawImage(pr.img, Math.round(x + box / 2 - s / 2), Math.round(y - 2), s, s);
      return true;
    }
    const have = (typeof window !== 'undefined' && window.CREW_ART && window.CREW_ART[race]) ? window.CREW_ART[race] : null;
    if (have) {
      const pose = have.idle_front ? 'idle_front' : have.idle_side ? 'idle_side' : Object.keys(have)[0];
      if (this.drawCrewPose(ctx, race, pose, false, Math.round(x + box / 2), Math.round(y + box + 1), box + 2)) return true;
    }
    const e = this.artEntry('crew_' + race + '_0');
    if (!e) return false;
    const lw = e.img.naturalWidth / 2, lh = e.img.naturalHeight / 2;
    ctx.drawImage(e.img, Math.round(x + (box - lw) / 2), Math.round(y + box - lh), lw, lh);
    return true;
  },

  // system icon art (icon_sys_<key>): the painted AI icon for a ship system, or null for
  // keys with no art yet (hull, sirensong) -> drawSysSym falls back to its vector silhouette.
  sysIcon(key) {
    if (key === 'hull' || key === 'sirensong' || key === 'open') return null;
    const e = this.artEntry('icon_sys_' + key);
    return e ? e.img : null;
  },

  // draw a full-bleed art image at logical size
  drawArt(ctx, name, x, y, w, h) {
    const e = this.artEntry(name);
    if (!e) return false;
    ctx.drawImage(e.img, x, y, w !== undefined ? w : e.img.naturalWidth / 2, h !== undefined ? h : e.img.naturalHeight / 2);
    return true;
  },

  // ----- FAMILIARS (bound spirits = our FTL drones) ------------------------------------
  // Hand-authored procedural sprites with animation states, drawn centred at (cx,cy).
  //   t      = animation clock (seconds)
  //   act    = 0..1 action phase (0 = idle; >0 = mid-action, e.g. firing / striking)
  //   deploy = 0..1 spawn phase (1 = fully present; <1 = scaling/fading in)
  // A future AI sheet `icon_fam_<key>` would win here; procedural is the fallback.
  drawFamiliar(ctx, key, cx, cy, scale, t, act, deploy) {
    act = act || 0; deploy = (deploy === undefined ? 1 : deploy); scale = scale || 1;
    if (deploy <= 0) return;
    const A = ctx;
    A.save();
    A.translate(cx, cy);
    A.scale(scale * (0.5 + 0.5 * deploy), scale * (0.5 + 0.5 * deploy)); // pop in on deploy
    A.globalAlpha = deploy;
    A.lineJoin = 'round'; A.lineCap = 'round';
    const baseA = deploy;
    const circ = (x, y, r) => { A.beginPath(); A.arc(x, y, r, 0, 7); A.fill(); };
    const ring = (x, y, r, w) => { A.lineWidth = w; A.beginPath(); A.arc(x, y, r, 0, 7); A.stroke(); };
    const tri = (ax, ay, bx, by, dx, dy) => { A.beginPath(); A.moveTo(ax, ay); A.lineTo(bx, by); A.lineTo(dx, dy); A.closePath(); A.fill(); };
    const glow = (col, r, a) => { A.globalAlpha = baseA * a; A.fillStyle = col; circ(0, 0, r); A.globalAlpha = baseA; };
    const flash = act > 0 ? Math.sin(Math.min(1, act) * Math.PI) : 0; // 0→1→0 over the action

    switch (key) {
      case 'emberimp': { // a candleflame imp (djinn / fire)
        glow(COL.fire2 || '#f08020', 8 + flash * 4, 0.22 + flash * 0.18);
        const lean = -act * 3, tipx = Math.sin(t * 11) * 1.6 + lean;
        A.fillStyle = '#c83a14'; // outer flame
        A.beginPath(); A.moveTo(tipx, -9 - flash * 2); A.quadraticCurveTo(5, 0, 0, 7); A.quadraticCurveTo(-5, 0, tipx, -9 - flash * 2); A.fill();
        A.fillStyle = COL.orange || '#f08020'; // mid flame
        A.beginPath(); A.moveTo(tipx * 0.7, -6); A.quadraticCurveTo(3.2, 0, 0, 5.5); A.quadraticCurveTo(-3.2, 0, tipx * 0.7, -6); A.fill();
        A.fillStyle = '#ffe27a'; circ(0, 1.5, 2.2 + flash); // ember core
        A.fillStyle = '#2a1206'; circ(-1.6, -1, 0.7); circ(1.6, -1, 0.7); // eyes
        const ey = ((t * 9) % 7); A.globalAlpha = baseA * (1 - ey / 7); A.fillStyle = '#ffd24a'; circ(1.5, -6 - ey, 0.7); A.globalAlpha = baseA; // rising ember
        if (flash > 0.3) { A.fillStyle = '#fff1c0'; circ(lean - 3, -7, 1.4 * flash); } // spark flung
        break;
      }
      case 'clockworkgull': { // brass mechanical gull (dwarf)
        glow(COL.gold || '#e6c878', 7, 0.16);
        const flap = Math.sin(t * 9) * (act > 0 ? 0.15 : 0.7) - act * 0.4;
        A.fillStyle = COL.brassdk || '#8a6a28';
        for (const s of [-1, 1]) { A.save(); A.scale(s, 1); A.rotate(-flap); tri(1, -1, 11, -5 - flap * 3, 4, 3); A.restore(); }
        A.fillStyle = COL.brass || '#caa24a'; A.beginPath(); A.ellipse(0, 1 + act * 2, 3.2, 5, 0, 0, 7); A.fill(); // body, dips on act
        A.fillStyle = COL.golddk || '#7d5f25'; tri(0, -3, -3, -6, 1, -5); // head/beak up-left
        A.fillStyle = COL.gold || '#e6c878'; circ(-0.5, -3.5, 1.4); // head
        A.fillStyle = '#2a1d10'; circ(-1, -3.6, 0.5); // eye
        A.strokeStyle = COL.golddk || '#7d5f25'; ring(0, 1, 1.6, 0.7); // gear detail
        break;
      }
      case 'squallsprite': { // a knot of wind + lightning (storm-elf)
        glow(COL.ltblue || '#6c9bd2', 8 + flash * 3, 0.2);
        A.save(); A.rotate(t * 1.6);
        A.strokeStyle = COL.cyan || '#7fd4d2'; A.lineWidth = 1.6;
        for (let i = 0; i < 3; i++) { A.save(); A.rotate(i * 2.1); A.beginPath(); A.arc(0, 0, 5 + i, -0.2, 2.4); A.stroke(); A.restore(); }
        A.restore();
        A.fillStyle = '#eaf6ff'; circ(0, 0, 2 + flash); // bright core
        if (flash > 0.2) { A.strokeStyle = '#dff2ff'; A.lineWidth = 1.2; A.beginPath(); A.moveTo(0, 0); A.lineTo(4, -3); A.lineTo(2, -1); A.lineTo(7, -6); A.stroke(); } // lightning on deflect
        break;
      }
      case 'countersigil': { // a floating rune-ward with an eye (dwarf)
        glow(COL.gold || '#e6c878', 7 + flash * 4, 0.16 + flash * 0.2);
        A.save(); A.rotate(t * 0.8);
        A.strokeStyle = COL.gold || '#e6c878'; ring(0, 0, 6, 1.3);
        A.lineWidth = 1; for (let i = 0; i < 6; i++) { const a = i * 1.05; A.beginPath(); A.moveTo(Math.cos(a) * 6, Math.sin(a) * 6); A.lineTo(Math.cos(a) * 7.6, Math.sin(a) * 7.6); A.stroke(); } // rune ticks
        A.restore();
        A.fillStyle = '#f6e6b0'; A.beginPath(); A.ellipse(0, 0, 3.2, 2, 0, 0, 7); A.fill(); // eye white
        A.fillStyle = '#27406e'; circ(0, 0, 1.2); // pupil
        if (flash > 0.3) { A.strokeStyle = '#fff4d0'; A.lineWidth = 1.4; A.beginPath(); A.moveTo(-6, -6); A.lineTo(6, 6); A.stroke(); } // cancel slash
        break;
      }
      case 'tinkerbeetles': { // a cluster of brass beetles (dwarf)
        glow(COL.gold || '#e6c878', 6 + flash * 3, 0.14 + flash * 0.18);
        const beetle = (bx, by, ph) => {
          const j = Math.sin(t * 12 + ph) * 0.8;
          A.strokeStyle = COL.golddk || '#7d5f25'; A.lineWidth = 0.7;
          for (const s of [-1, 1]) { A.beginPath(); A.moveTo(bx, by); A.lineTo(bx + s * 2.4, by + j); A.stroke(); A.beginPath(); A.moveTo(bx, by + 1.2); A.lineTo(bx + s * 2.4, by + 1.6 - j); A.stroke(); }
          A.fillStyle = COL.brass || '#caa24a'; A.beginPath(); A.ellipse(bx, by + j * 0.3, 2.2, 2.8, 0, 0, 7); A.fill();
          A.strokeStyle = COL.golddk; A.lineWidth = 0.6; A.beginPath(); A.moveTo(bx, by - 2 + j * 0.3); A.lineTo(bx, by + 2.5 + j * 0.3); A.stroke();
        };
        beetle(-3.5, 1, 0); beetle(3.5, 0, 2.0); beetle(0, -3, 4.1);
        if (flash > 0.2) for (let i = 0; i < 4; i++) { A.globalAlpha = baseA * flash; A.fillStyle = '#ffe27a'; circ(Math.cos(i * 1.6) * (4 + flash * 3), Math.sin(i * 1.6) * (4 + flash * 3) - 2, 0.9); A.globalAlpha = baseA; }
        break;
      }
      case 'coralsentinel': { // a coral golem standing guard (merfolk)
        glow(COL.teal || '#3a8f86', 8, 0.16);
        const sway = Math.sin(t * 2) * 1.2, armUp = -act * 5;
        A.fillStyle = '#2f6f66'; A.beginPath(); A.ellipse(sway * 0.4, 1, 4.5, 6, 0, 0, 7); A.fill(); // torso
        A.fillStyle = COL.teal || '#3a8f86'; circ(sway * 0.5, -6, 3); // head
        A.fillStyle = '#79c4b8';
        A.save(); A.translate(-4, -1); A.rotate(0.3 + armUp * 0.1); A.fillRect(-1.2, 0, 2.4, 6); A.restore(); // left arm
        A.save(); A.translate(4, -1); A.rotate(-0.3 - armUp * 0.12 + act * 0.6); A.fillRect(-1.2, 0, 2.4, 6); A.restore(); // right arm (stomps)
        A.fillStyle = COL.pink || '#d98ab0'; for (const c of [[-2, -8], [2, -8.5], [0, -9.5], [4, -5]]) tri(c[0], c[1], c[0] - 1.4, c[1] + 2.4, c[0] + 1.4, c[1] + 2.4); // coral nubs
        if (flash > 0.4) { A.strokeStyle = '#bfe8e4'; ring(4, 7, 2 + flash * 4, 1); } // stomp shock
        break;
      }
      case 'reefsingers': { // singing merfolk sprites (merfolk / mend)
        glow(COL.teal || '#3a8f86', 7, 0.16);
        const bob = Math.sin(t * 2.4) * 1.2;
        for (const s of [-1, 1]) { A.save(); A.translate(s * 3, bob * s * 0.6);
          A.fillStyle = '#79c4b8'; circ(0, -3, 2); // head
          A.fillStyle = COL.teal || '#3a8f86'; tri(0, -1, -2.4, 5, 2.4, 5); // body/tail
          A.restore();
        }
        const ny = (t * 6) % 9; // rising music notes
        A.globalAlpha = baseA * (1 - ny / 9) * (0.6 + flash); A.fillStyle = COL.pink || '#d98ab0';
        circ(2, -5 - ny, 1.1); A.fillRect(2.8, -10 - ny, 0.8, 4);
        A.globalAlpha = baseA * (1 - ((ny + 4) % 9) / 9) * 0.7; circ(-3, -5 - ((ny + 4) % 9), 1); A.fillRect(-2.3, -9 - ((ny + 4) % 9), 0.7, 3.5);
        A.globalAlpha = baseA;
        break;
      }
      case 'brassjanissary': { // a soldier folded from lamplight (djinn / boarder)
        glow(COL.fire2 || '#f08020', 8 + flash * 3, 0.18 + flash * 0.12);
        const lunge = act * 4;
        A.fillStyle = COL.brassdk || '#8a6a28'; A.fillRect(-2.4 + lunge * 0.4, -4, 4.8, 9); // torso
        A.fillStyle = COL.brass || '#caa24a'; circ(lunge * 0.4, -6, 2.4); // head
        A.fillStyle = COL.golddk || '#7d5f25'; A.fillRect(-2.4 + lunge * 0.4, 4, 1.8, 4); A.fillRect(0.6 + lunge * 0.4, 4, 1.8, 4); // legs
        A.save(); A.translate(2 + lunge, -3); A.rotate(-0.6 + act * 1.8); // scimitar, swung on act
        A.strokeStyle = flash > 0.2 ? '#fff1c0' : (COL.gold || '#e6c878'); A.lineWidth = 1.6;
        A.beginPath(); A.arc(0, 4, 7, -1.3, 0.2); A.stroke();
        A.restore();
        if (flash > 0.3) { A.strokeStyle = 'rgba(255,240,190,' + flash.toFixed(2) + ')'; A.lineWidth = 1.4; A.beginPath(); A.arc(3 + lunge, -2, 8, -1.1, 0.6); A.stroke(); } // slash arc
        break;
      }
      default: { glow(COL.white, 6, 0.2); A.fillStyle = COL.white; circ(0, 0, 3); }
    }
    A.restore();
  },

  // build a canvas from a pixel grid (array of strings) + char->color map
  px(grid, map, scale) {
    scale = scale || 1;
    const h = grid.length, w = grid[0].length;
    const cv = document.createElement('canvas');
    cv.width = w * scale; cv.height = h * scale;
    const c = cv.getContext('2d');
    for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) {
      const ch = grid[y][x];
      if (ch === '.' || ch === ' ') continue;
      c.fillStyle = map[ch] || COL.white;
      c.fillRect(x * scale, y * scale, scale, scale);
    }
    return cv;
  },

  cached(key, builder) {
    let cv = this._cache.get(key);
    if (!cv) { cv = builder(); this._cache.set(key, cv); }
    return cv;
  },

  // ============ CREW SPRITES (12x14, 2 frames, facing right) ============
  crewBody(race) {
    // returns {rows0to9, legsA(4 rows), legsB(4 rows), map}
    const B = {
      human: {
        body: [
          '....hhhh....',
          '...hhhhhh...',
          '...hssssh...',
          '...sseses...',
          '...ssssss...',
          '....ssss....',
          '..cccccccc..',
          '.scctcctccs.',
          '.sccccccccs.',
          '..cccccccc..',
        ],
        map: { h: '#6b4a2e', s: COL.skin, e: '#1a1832', c: '#27406e', t: COL.gold, p: '#7a5a36', b: '#2a2a3a', d: '#27406e' },
      },
      merfolk: {
        body: [
          '.....hh.h...',
          '....hhhhh...',
          '...hssssh...',
          '...sseses...',
          '...ssssss...',
          '....ssss....',
          '..cccccccc..',
          '.scctcctccs.',
          '.sccccccccs.',
          '..cccccccc..',
        ],
        map: { h: COL.teal, s: '#79c4b8', e: '#0e2440', c: '#3a6ec8', t: COL.cyan, p: '#27498f', b: '#1d4474', d: '#3a6ec8' },
      },
      djinn: {
        body: [
          '...F.fF.....',
          '..fFfFfF....',
          '...hssssh...',
          '...sseses...',
          '...ssssss...',
          '....ssss....',
          '..cccccccc..',
          '.scctcctccs.',
          '.sccccccccs.',
          '..cccccccc..',
        ],
        map: { F: COL.fire1, f: COL.fire2, h: COL.fire2, s: '#e07830', e: '#f8d850', c: '#b08020', t: COL.fire1, p: '#7c1c28', b: '#4a2c66', d: '#b08020' },
      },
      stormelf: {
        body: [
          '....hhhh....',
          '...hhhhhh...',
          '..EhssssH...',
          '...sseses...',
          '...ssssss...',
          '....ssss....',
          '..cccccccc..',
          '.scctcctccs.',
          '.sccccccccs.',
          '..cccccccc..',
        ],
        map: { h: '#e8e8f4', E: '#e8d8d0', H: '#e8e8f4', s: '#e8d8d0', e: '#3458a8', c: '#6c9bd2', t: COL.white, p: '#494f63', b: '#2a3f73', d: '#6c9bd2' },
      },
      dwarf: {
        body: [
          '...mmmmmm...',
          '..mmmmmmmm..',
          '...mssssm...',
          '...sseses...',
          '...hhhhhh...',
          '...hhhhhh...',
          '..cchhhhcc..',
          '.sccthhtccs.',
          '.sccccccccs.',
          '..cccccccc..',
        ],
        map: { m: '#8c93a6', h: '#c06a28', s: COL.skin, e: '#1a1832', c: '#5e3a22', t: COL.golddk, p: '#494f63', b: '#2a2a3a', d: '#5e3a22' },
      },
      lizard: {
        body: [
          '....KKK.....',
          '...ssssss...',
          '...ssssssss.',
          '...sseses.s.',
          '...ssssssss.',
          '....ssss....',
          '..cccccccc..',
          '.gcctcctccg.',
          '.gccccccccg.',
          'g.cccccccc..',
        ],
        map: { K: '#8fd45a', s: '#3f9850', g: '#3f9850', e: COL.gold, c: '#5e3a22', t: COL.golddk, p: '#1f5c38', b: '#143818', d: '#1f5c38' },
      },
      siren: {
        body: [
          '....hhhh....',
          '...hhhhhh...',
          '..hhsssshh..',
          '..hsseseshh.',
          '..hssssss.h.',
          '..h.ssss..h.',
          '..hdddddddh.',
          '.sddtddtdds.',
          '.sdddddddds.',
          '..dddddddd..',
        ],
        map: { h: '#7fd4d2', s: '#f0e0d8', e: '#7c4ca0', d: '#7c4ca0', t: COL.pink, p: '#7c4ca0', b: '#f0e0d8', c: '#7c4ca0' },
      },
    };
    const def = B[race] || B.human;
    const legsA = [
      '...pppppp...',
      '...pp..pp...',
      '...bb..bb...',
      '..bbb..bbb..',
    ];
    const legsB = [
      '...pppppp...',
      '..pp....pp..',
      '..bb....bb..',
      '.bbb....bbb.',
    ];
    if (race === 'siren') {
      return { body: def.body, map: def.map,
        legsA: ['...dddddd...', '..dddddddd..', '..dddddddd..', '...b.b..b.b.'],
        legsB: ['...dddddd...', '..dddddddd..', '.dddddddddd.', '..b.b..b.b..'] };
    }
    if (race === 'lizard') {
      return { body: def.body, map: def.map,
        legsA: ['gg.pppppp...', '.g.pp..pp...', '...bb..bb...', '..bbb..bbb..'],
        legsB: ['gg.pppppp...', '.gpp....pp..', '..bb....bb..', '.bbb....bbb.'] };
    }
    return { body: def.body, map: def.map, legsA, legsB };
  },

  crew(race, frame, flip) {
    const key = 'crew|' + race + '|' + frame + '|' + (flip ? 1 : 0);
    return this.cached(key, () => {
      const d = this.crewBody(race);
      const grid = d.body.concat(frame ? d.legsB : d.legsA);
      let cv = this.px(grid, d.map);
      if (flip) {
        const f = document.createElement('canvas');
        f.width = cv.width; f.height = cv.height;
        const c = f.getContext('2d');
        c.translate(cv.width, 0); c.scale(-1, 1);
        c.drawImage(cv, 0, 0);
        cv = f;
      }
      return cv;
    });
  },

  // crew portrait (head only, 10x10, boxed)
  portrait(race) {
    return this.cached('port|' + race, () => {
      const d = this.crewBody(race);
      const grid = d.body.slice(0, 6).map(r => r.slice(1, 11));
      const cv = document.createElement('canvas');
      cv.width = 12; cv.height = 12;
      const c = cv.getContext('2d');
      c.fillStyle = COL.dkblue; c.fillRect(0, 0, 12, 12);
      c.drawImage(this.px(grid, d.map), 1, 2);
      return cv;
    });
  },

  // ============ SYSTEM ICONS (10x10) ============
  icon(name) {
    return this.cached('icon|' + name, () => {
      const G = {
        helm: { g: [
          '....XX....', '.X..XX..X.', '..X.XX.X..', '...XXXX...', 'XXXX..XXXX',
          'XXXX..XXXX', '...XXXX...', '..X.XX.X..', '.X..XX..X.', '....XX....'],
          m: { X: COL.gold } },
        sails: { g: [
          '....M.....', '....MS....', '....MSS...', '....MSSS..', '....MSSSS.',
          '....MSSS..', '....MSS...', '....MS....', '....M.....', '..MMMMM...'],
          m: { M: COL.woodlt, S: COL.sail } },
        wards: { g: [
          '.BBBBBBBB.', 'BCCCCCCCCB', 'BCCWCCCCCB', 'BCCCCCCCCB', 'BCCCCCCCCB',
          '.BCCCCCCB.', '.BCCCCCCB.', '..BCCCCB..', '...BCCB...', '....BB....'],
          m: { B: COL.dkblue, C: COL.cyan, W: COL.white } },
        weapons: { g: [
          '..........', '..........', '.XXXXXXXX.', 'XXXXXXXXXX', '.XXXXXXXX.',
          '....WW....', '...WWWW...', '...WWWW...', '....WW....', '..........'],
          m: { X: COL.dkgrey, W: COL.wood } },
        infirmary: { g: [
          '.WWWWWWWW.', 'WWWWRRWWWW', 'WWWWRRWWWW', 'WWRRRRRRWW', 'WWRRRRRRWW',
          'WWWWRRWWWW', 'WWWWRRWWWW', 'WWWWWWWWWW', '.WWWWWWWW.', '..........'],
          m: { W: COL.white, R: COL.red } },
        doors: { g: [
          '.XXXXXXXX.', '.XWWWWWWX.', '.XWWWWWWX.', '.XWWWWWWX.', '.XWWWWGWX.',
          '.XWWWWWWX.', '.XWWWWWWX.', '.XWWWWWWX.', '.XXXXXXXX.', '..........'],
          m: { X: COL.wooddk, W: COL.wood, G: COL.gold } },
        lookout: { g: [
          '..........', '..XXXXXX..', '.X......X.', 'X...BB...X', 'X..BWB...X',
          'X...BB...X', '.X......X.', '..XXXXXX..', '..........', '..........'],
          m: { X: COL.ltgrey, B: COL.dkblue, W: COL.white } },
        sump: { g: [
          '..XXXXXX..', '..X....X..', '..X.CC.X..', '..X.CC.X..', 'XXXX.CXXXX',
          'X..C.C...X', 'X.C..C.C.X', 'X..CCCC..X', 'XCCCCCCCCX', 'XXXXXXXXXX'],
          m: { X: COL.dkgrey, C: COL.cyan } },
        shrine: { g: [
          '....GG....', '...GCCG...', '...GCCG...', '....GG....', '..WWWWWW..',
          '...WWWW...', '...WWWW...', '...WWWW...', '..WWWWWW..', '.WWWWWWWW.'],
          m: { G: COL.gold, C: COL.cyan, W: '#7a5230' } },
        breach: { g: [
          '.W......W.', 'W.KKKK..W.', '.KKKKKKK..', 'KKKKKKKKK.', '.KKKKKKKKW',
          'WKKKKKKKK.', '.KKKKKKK..', '..KKKKKKW.', '.W.KKKK...', '....W..W..'],
          m: { K: '#100c14', W: '#d8c8a8' } },
        core: { g: [
          '....CC....', '...CCCC...', '..CCWCCC..', '.CCCWCCCC.', '.CCCCCCCC.',
          '..CCCCCC..', '...CCCC...', '....CC....', '...mmmm...', '..mmmmmm..'],
          m: { C: COL.cyan, W: COL.white, m: COL.dkgrey } },
        brinegate: { g: [
          '..PPPPPP..', '.P......P.', 'P..CCCC..P', 'P.C....C.P', 'P.C.WW.C.P',
          'P.C.WW.C.P', 'P.C....C.P', 'P..CCCC..P', '.P......P.', '..PPPPPP..'],
          m: { P: COL.purple, C: COL.cyan, W: COL.white } },
        fogveil: { g: [
          '..........', '.GGG..GG..', 'G...GG..G.', '..........', '..GG...GG.',
          '.G..GGG..G', '..........', 'GG..GG..G.', '..GG..GG..', '..........'],
          m: { G: COL.ltgrey } },
        cargo: { g: [
          '.XXXXXXXX.', '.XWXXXXWX.', '.XXWXXWXX.', '.XXXWWXXX.', '.XXXWWXXX.',
          '.XXWXXWXX.', '.XWXXXXWX.', '.XXXXXXXX.', '..........', '..........'],
          m: { X: COL.wood, W: COL.wooddk } },
        shard: { g: [
          '....G.....', '...GGG....', '..GGWGG...', '.GGGWGGG..', '..GGGGG...',
          '...GGG....', '....G.....', '..........', '..........', '..........'],
          m: { G: COL.gold, W: COL.white } },
        runeshot: { g: [
          '...RRRR...', '..RWWRRR..', '.RWRRRRRR.', '.RRRRRRRR.', '.RRRRRRRR.',
          '..RRRRRR..', '...RRRR...', '..........', '..........', '..........'],
          m: { R: COL.dkred, W: COL.pink } },
        hull: { g: [
          '..........', 'S...M...S.', 'SS..M..SS.', 'XXXXXXXXXX', '.XXXXXXXX.',
          '..XXXXXX..', '..........', '..........', '..........', '..........'],
          m: { X: COL.wood, M: COL.woodlt, S: COL.sail } },
        skull: { g: [
          '..XXXXXX..', '.XXXXXXXX.', '.XBBXXBBX.', '.XBBXXBBX.', '.XXXXXXXX.',
          '..XXXXXX..', '..X.XX.X..', '..........', '..........', '..........'],
          m: { X: COL.ltgrey, B: COL.black } },
        flame: { g: [
          '....R.....', '...RR..R..', '...RRR.R..', '..RRYRRR..', '..RYYYR...',
          '.RRYYYRR..', '.RYYWYYR..', '..RYYYR...', '...RRR....', '..........'],
          m: { R: COL.fire2, Y: COL.fire1, W: COL.white } },
        drop: { g: [
          '....W.....', '....WW....', '...WWWW...', '..WWWWWW..', '..WWWWWW..',
          '..WWWWWW..', '...WWWW...', '..........', '..........', '..........'],
          m: { W: COL.water } },
        anchor: { g: [
          '....XX....', '...X..X...', '....XX....', '....X.....', '..XXXXX...',
          '....X.....', 'X...X...X.', 'X...X...X.', '.X..X..X..', '..XXXXX...'],
          m: { X: COL.ltgrey } },
      };
      const d = G[name] || G.cargo;
      return this.px(d.g, d.m);
    });
  },

  // ============ WEAPON DECK SPRITES (16x8, facing right) ============
  // per-weapon distinctive sprites: every gun has a memorable silhouette tied to
  // what it does (slim iron, fat bands, bells, prongs, pots, crystals, horns...)
  weaponArt(key) {
    const e = this.artEntry('weapon_' + key);
    if (e) return e.img; // imported AI sprite (96x48 file)
    const def = SPR.WPN_PX[key];
    if (!def) return null;
    return this.cached('wart|' + key, () => this.px(def.g, def.m, 1));
  },
  // UI-chip version: baked, area-averaged 32x16 - crisp at chip size where the
  // full-res art garbles under NEAREST downscaling
  weaponIcon(key) {
    // prefer the FULL-res weapon art (downsamples crisp at any display size);
    // the small _icon (sized for the classic 2x view) upscales/blurs on big HD windows
    const full = this.weaponArt(key);
    if (full) return full;
    const e = this.artEntry('weapon_' + key + '_icon');
    return e ? e.img : null;
  },

  WPN_PX: {
    // ---- placeholder pixel sprites for the new families (AI art later) ----
    chainculverin: { g: [
      '................', '..BBBBBBBBBBBBb.', '..BgBgBgBgBgBBb.', '..BBBBBBBBBBBBb.',
      '.....WWW...g....', '....WWWWW.g.g...', '.....WW....g....', '................'],
      m: { B: '#3a3a4a', b: '#9aa0ae', g: '#c8a040', W: '#7a5230' } },
    langrage: { g: [
      '................', '...BBBBBBBBb....', '...BBBBBBBBb.s..', '....s..s..s.s.s.',
      '...s.s.s.s...s..', '....WWWW..s.....', '...WWWWW........', '................'],
      m: { B: '#3a3a4a', b: '#9aa0ae', s: '#9aa0ae', W: '#7a5230' } },
    cogtorpedo: { g: [
      '................', '................', '..ggBBBBBBBB>...', '..ggBBBBBBBB>>..',
      '..ggBBBBBBBB>...', '....g....g......', '................', '................'],
      m: { B: '#3a3a4a', g: '#c8a040', '>': '#7c1c28' } },
    forgetwins: { g: [
      '................', '..ooBBBBBBB>....', '..ooBBBBBBB>>...', '................',
      '..ooBBBBBBB>....', '..ooBBBBBBB>>...', '................', '................'],
      m: { B: '#3a3a4a', o: '#e07830', '>': '#7c1c28' } },
    petardrune: { g: [
      '................', '......gggg......', '....ggGGGGgg....', '....gGgGGgGg....',
      '....ggGGGGgg....', '......gggg......', '.......WW.......', '................'],
      m: { g: '#c8a040', G: '#f0c050', W: '#7a5230' } },
    nullrune: { g: [
      '................', '......cccc......', '....ccCCCCcc....', '....cC.cc.Cc....',
      '....ccCCCCcc....', '......cccc......', '.......WW.......', '................'],
      m: { c: '#5a7a9a', C: '#9ec4e8', W: '#7a5230' } },
    barnaclebomb: { g: [
      '................', '.....w.ww.w.....', '....wWWWWWWw....', '....WWwWWwWW....',
      '....wWWWWWWw....', '.....w.ww.w.....', '.......WW.......', '................'],
      m: { w: '#2a6a8a', W: '#58b8d8', '.': null } },
    slumberveil: { g: [
      '................', '......pppp......', '....ppPPPPpp....', '....pPzPPzPp....',
      '....ppPPPPpp....', '......pppp......', '.......WW.......', '................'],
      m: { p: '#a05a86', P: '#e08ab0', z: '#f4fafc', W: '#7a5230' } },
    mendingtide: { g: [
      '................', '......gggg......', '....ggGGGGgg....', '....gG+GG+Gg....',
      '....ggGGGGgg....', '......gggg......', '.......WW.......', '................'],
      m: { g: '#2e8b4f', G: '#7ac890', '+': '#f4fafc', W: '#7a5230' } },
    emberlens: { g: [
      '................', '....bbb.........', '...bOOOb........', '...bOOOb====....',
      '...bOOOb........', '....bbb.WW......', '.......WWW......', '................'],
      m: { b: '#c8a040', O: '#ffb050', '=': '#ffd890', W: '#7a5230' } },
    noonglass: { g: [
      '................', '...bbbb.........', '..bGGGGb........', '..bGGGGb=====...',
      '..bGGGGb........', '...bbbb.WW......', '.......WWW......', '................'],
      m: { b: '#c8a040', G: '#ffe890', '=': '#fff4c0', W: '#7a5230' } },
    wildfirebeam: { g: [
      '................', '...bbb..........', '..bFfFb.........', '..bfFfb=~=~=....',
      '..bFfFb.........', '...bbb..WW......', '.......WWW......', '................'],
      m: { b: '#7a5230', F: '#e04830', f: '#ffb050', '=': '#ffb050', '~': '#e04830' } },
    stormlash: { g: [
      '................', '....BBBb........', '...BcccBb.......', '...Bccc.c.c.....',
      '...BcccB.c.c....', '....BBBb..c.....', '......WW........', '................'],
      m: { B: '#3a3a4a', b: '#9aa0ae', c: '#f4fafc', W: '#7a5230' } },
    thunderhead: { g: [
      '................', '...BBBBb..c.....', '..BccccBb.cc....', '..Bcccc.ccc.....',
      '..BccccBbcc.....', '...BBBBb..c.....', '......WW........', '................'],
      m: { B: '#3a3a4a', b: '#9aa0ae', c: '#58b8d8', W: '#7a5230' } },
    augershot: { g: [
      '................', '...wWBBBBBb.....', '..wWwWBBBBBb>...', '..WwWwBBBBBb>>..',
      '..wWwWBBBBBb>...', '...wWBBBBBb.....', '......WW........', '................'],
      m: { w: '#2a6a8a', W: '#58b8d8', B: '#3a3a4a', b: '#9aa0ae', '>': '#9ec4e8' } },
    quillstorm: { g: [
      '................', '...GG...../.....', '..GggG.../......', '..GggG../..../..',
      '..GggG...../....', '...GG.../.......', '................', '................'],
      m: { G: '#4a7a3a', g: '#9ad84a', '/': '#9ad84a' } },
    sirenlure: { g: [
      '................', '.....pp.........', '....pPPp...~....', '....pPPpp.~.~...',
      '.....pPPp..~....', '......ppp~......', '......WW........', '................'],
      m: { p: '#a05a86', P: '#e08ab0', '~': '#f4cce0', W: '#7a5230' } },
    lightcannon: { g: [
      '................', '................', '....BBBBBBBBBBb.', '....BBBBBBBBBBb.',
      '.....WWW........', '....WWWWW.......', '.....WW.........', '................'],
      m: { B: '#3a3a4a', b: '#9aa0ae', W: '#7a5230' } },
    chainshot: { g: [
      '................', '....BBBBBBBBBBb.', '....BBBBBBBBBBb.', '.............c..',
      '.....WWW....c.c.', '....WWWWW....c..', '.....WW.........', '................'],
      m: { B: '#3a3a4a', b: '#9aa0ae', c: '#9ec4e8', W: '#7a5230' } },
    swivels: { g: [
      '...BBBBBBBBBb...', '................', '...BBBBBBBBBb...', '......g.........',
      '.....ggg........', '.....WWW........', '....WWWWW.......', '................'],
      m: { B: '#3a3a4a', b: '#9aa0ae', g: '#f0c050', W: '#7a5230' } },
    heavycannon: { g: [
      '................', '..BBBBBBBBBBBB..', '..BBrBBBBrBBBBb.', '..BBrBBBBrBBBBb.',
      '..BBBBBBBBBBBB..', '....WWWWW.......', '...WWWWWWW......', '................'],
      m: { B: '#3a3a4a', b: '#9aa0ae', r: '#7c1c28', W: '#7a5230' } },
    carronade: { g: [
      '................', '.....BBBBBBBo...', '....BBBBBBBBoo..', '....BBBBBBBBoo..',
      '.....BBBBBBBo...', '....WWWWW.......', '...WWWWWWW......', '................'],
      m: { B: '#3a3a4a', o: '#e07830', W: '#7a5230' } },
    runebombard: { g: [
      '................', '..BBBBBBBBBBBb..', '..BBBPPBBBBBBb..', '..BBBPPBBBBBBb..',
      '..BBBBBBBBBBBb..', '....WWWWW.......', '...WWWWWWW......', '................'],
      m: { B: '#3a3a4a', b: '#9aa0ae', P: '#e08ab0', W: '#7a5230' } },
    grapeshot: { g: [
      '................', '....BBBBBBBg....', '....BBBBBBBgg...', '....BBBBBBBggg..',
      '....BBBBBBBgg...', '.....WWWW..g....', '....WWWWW.......', '................'],
      m: { B: '#3a3a4a', g: '#f0c050', W: '#7a5230' } },
    broadside: { g: [
      '..BBBBBBBBBb....', '................', '..BBBBBBBBBBBb..', '................',
      '..BBBBBBBBBb....', '.....WWWW.......', '....WWWWWW......', '................'],
      m: { B: '#3a3a4a', b: '#9aa0ae', W: '#7a5230' } },
    depleteduranium: { g: [
      '................', '.BBBBBBBBBBBBBL.', '.BLLBBLLBBLLBBL.', '.BBBBBBBBBBBBBL.',
      '................', '.....WWWW.......', '....WWWWWW......', '................'],
      m: { B: '#2c2c38', L: '#a8e858', W: '#7a5230' } },
    flamelance: { g: [
      '..............F.', '....SSSSSSSSSFF.', '....SSSSSSSSSFFF', '..............FF',
      '.....WW.......F.', '....WWWW........', '.....WW.........', '................'],
      m: { S: '#4a3a3a', F: '#f08030', W: '#7a5230' } },
    tidelance: { g: [
      '................', '....uuuuuuuuuC..', '....uuuuuuuuuCC.', '....uuuuuuuuuC..',
      '.............C..', '.....WWW......C.', '....WWWWW.......', '................'],
      m: { u: '#d8b890', C: '#3a78c8', W: '#7a5230' } },
    inkjet: { g: [
      '................', '....PPPP........', '...PPPPPPSSSSb..', '...PPPPPPSSSSb..',
      '....PPPP........', '.....WWW........', '....WWWWW.......', '................'],
      m: { P: '#6a3a8a', S: '#3a3a4a', b: '#b08ad0', W: '#7a5230' } },
    sparkbolt: { g: [
      '.............Y..', '....SSSSSSSSY...', '....SSSSSSSSSYY.', '............Y...',
      '.....WW......Y..', '....WWWW........', '.....WW.........', '................'],
      m: { S: '#4a4a5a', Y: '#f0e060', W: '#7a5230' } },
    tempestchain: { g: [
      '....SSSSSSSSSC..', '.............cC.', '....SSSSSSSSSC..', '................',
      '.....WW.........', '....WWWW........', '.....WW.........', '................'],
      m: { S: '#4a4a5a', C: '#7fd4d2', c: '#bfe8e4', W: '#7a5230' } },
    galeshear: { g: [
      '..........A.....', '....SSSSSAAA....', '....SSSSSSAAAA..', '....SSSSSAAA....',
      '..........A.....', '.....WWW........', '....WWWWW.......', '................'],
      m: { S: '#4a4a5a', A: '#e8e0c8', W: '#7a5230' } },
    venomdart: { g: [
      '................', '....SSSSSSSSSSG.', '..............G.', '.....WW.......G.',
      '....WWWW........', '.....WW.........', '................', '................'],
      m: { S: '#4a4a5a', G: '#58c048', W: '#7a5230' } },
    cindervolley: { g: [
      '...SSSSSSSf.....', '................', '...SSSSSSSSf....', '................',
      '...SSSSSSSf.....', '.....WWWW.......', '....WWWWW.......', '................'],
      m: { S: '#4a3a3a', f: '#f08030', W: '#7a5230' } },
    brinevolley: { g: [
      '...SSSSSSSC.....', '................', '...SSSSSSSSC....', '................',
      '...SSSSSSSC.....', '.....WWWW.......', '....WWWWW.......', '................'],
      m: { S: '#3a4252', C: '#3a78c8', W: '#7a5230' } },
    infernobomb: { g: [
      '..........s.....', '.........sF.....', '....KKKK.F......', '...KKKKKK.......',
      '...KKFFKK.......', '...KKKKKK.......', '....KKKK........', '....WWWW........'],
      m: { K: '#26202c', F: '#f08030', s: '#9aa0ae', W: '#7a5230' } },
    maelstrom: { g: [
      '..........s.....', '.........sC.....', '....KKKK........', '...KKCCKK.......',
      '...KCKKCK.......', '...KKCCKK.......', '....KKKK........', '....WWWW........'],
      m: { K: '#26202c', C: '#3a78c8', s: '#9aa0ae', W: '#7a5230' } },
    seekertorpedo: { g: [
      '................', '..f.............', '..ffSSSSSSSSEb..', '..ffSSSSSSSSEb..',
      '..f.............', '.....WWWW.......', '....WWWWW.......', '................'],
      m: { f: '#e07830', S: '#3a4252', E: '#f4f4ec', b: '#9aa0ae', W: '#7a5230' } },
    phoenixbeam: { g: [
      '...F.......F....', '...FF.TTT.FF....', '....FFTTTFF.....', '.....FTTTF......',
      '......TTT.......', '.....WWWW.......', '....WWWWWW......', '................'],
      m: { F: '#f08030', T: '#f4f4ec', W: '#7a5230' } },
    dirgebeam: { g: [
      '....PPPPP.......', '...PPTTTPP......', '...PT.T.TP......', '...PPTTTPP......',
      '....PPPPP.......', '.....WWWW.......', '................', '................'],
      m: { P: '#6a3a8a', T: '#e8e0d8', W: '#7a5230' } },
    wailhorn: { g: [
      '.....mmmm.......', '...mmmppmm......', '..mmpppppmm.....', '..mpp..ppmm.....',
      '..mpppppmm......', '...mmmmmm.......', '.....WWWW.......', '................'],
      m: { m: '#e8e0d8', p: '#e08ab0', W: '#7a5230' } },
  },

  weaponSprite(family, tint) {
    return this.cached('wpn|' + family + '|' + tint, () => {
      const T = tint;
      const G = {
        cannon: { g: [
          '................',
          '......BBBBBBBB..',
          '..BBBBBBBBBBBBBb',
          '..BBBBBBBBBBBBBb',
          '......BBBBBB....',
          '....WWWW........',
          '...WWWWWW.......',
          '....WWWW........'],
          m: { B: '#3a3a4a', b: T, W: COL.wood } },
        magic: { g: [
          '..........TOO...',
          '.........TOOOO..',
          '.........TOOOO..',
          '......SSSTOO....',
          '...SSS..........',
          '...WW...........',
          '..WWWW..........',
          '...WW...........'],
          m: { O: T, T: COL.white, S: '#3a3a4a', W: COL.wood } },
        bomb: { g: [
          '................',
          '.........BBBB...',
          '.......BBBBBBb..',
          '....BBBBBBBBb...',
          '...BBBBBBBB.....',
          '...WWWW.........',
          '..WWWWWW........',
          '...WWWW.........'],
          m: { B: '#3a3a4a', b: T, W: COL.wood } },
        beam: { g: [
          '................',
          '......CCCCCCCCT.',
          '..BBBCCCCCCCCCTT',
          '..BBBCCCCCCCCCTT',
          '......CCCCCCCCT.',
          '....WWW.........',
          '...WWWWW........',
          '....WWW.........'],
          m: { B: '#3a3a4a', C: T, T: COL.white, W: COL.wood } },
        horn: { g: [
          '............TT..',
          '..........TTTT..',
          '....HHHHHHTTT...',
          '..HHHHHHHHTT....',
          '..HHHH..........',
          '...WW...........',
          '..WWWW..........',
          '...WW...........'],
          m: { H: T, T: COL.white, W: COL.wood } },
      };
      const d = G[family] || G.cannon;
      return this.px(d.g, d.m);
    });
  },

  // ============ PROJECTILES ============
  proj(type, frame) {
    return this.cached('proj|' + type + '|' + (frame || 0), () => {
      const G = {
        ball: { g: ['XX.', 'XXX', '.XX'], m: { X: '#2a2a3a' } },
        ball2: { g: ['.XX', 'XXX', 'XX.'], m: { X: '#2a2a3a' } },
        fire: { g: ['..YR.', '.YYRR', 'RYWYR', '.YYR.', '..R..'], m: { Y: COL.fire1, R: COL.fire2, W: COL.white } },
        fire2: { g: ['.RY..', 'RRYY.', 'RYWYR', '.RYY.', '..Y..'], m: { Y: COL.fire1, R: COL.fire2, W: COL.white } },
        bubble: { g: ['.BB.', 'BWBB', 'BBBB', '.BB.'], m: { B: COL.water, W: COL.white } },
        note: { g: ['..XX.', '..XXX', '..X..', 'XXX..', 'XXX..'], m: { X: COL.pink } },
        torpedo: { g: ['..RRRRRR', 'RRRRRRRW', '..RRRRRR'], m: { R: COL.dkred, W: COL.white } },
        bombproj: { g: ['..FF..', '.XXXX.', 'XXXXXX', 'XXXXXX', '.XXXX.'], m: { X: '#3a3a4a', F: COL.fire1 } },
        ion: { g: ['.CC.', 'CWWC', 'CWWC', '.CC.'], m: { C: COL.cyan, W: COL.white } },
        venom: { g: ['.GG.', 'GLLG', '.GG.'], m: { G: COL.dkgreen, L: COL.lime } },
        // dwarven auger: a steel drill bit (tip points right, toward the enemy)
        drill: { g: ['.SS..', 'SSSSW', 'SSSSS', 'SSSSW', '.SS..'], m: { S: '#9aa0ae', W: COL.white } },
        // lizard quills: barbed spines with poison-green tips
        quill: { g: ['X...G', '.XXXG', 'X...G'], m: { X: '#8a6a3a', G: COL.lime } },
        // brine wave: a curling water crest
        wave: { g: ['..WW', '.WBB', 'WBBB', 'BBB.'], m: { B: COL.water, W: COL.white } },
        // gale gust: a pale wind swirl
        gust: { g: ['.WWW', 'WW..', '.WWW', '...W'], m: { W: '#dfeaf0' } },
        // kraken ink: a dark blot
        ink: { g: ['.KK.', 'KPPK', 'KKKK', '.KK.'], m: { K: '#140f1e', P: COL.dkpurple } },
      };
      const d = G[type] || G.ball;
      return this.px(d.g, d.m);
    });
  },

  // flame animation for burning rooms (8x10)
  flame(frame) {
    return this.cached('flameanim|' + frame, () => {
      const f1 = ['...R....', '..RR..R.', '..RRR.R.', '.RRYRRR.', '.RYYYR..', 'RRYYYRR.', 'RYYWYYR.', '.RYYYR..'];
      const f2 = ['....R...', '.R..RR..', '.R.RRR..', '.RRRYRR.', '..RYYYR.', '.RRYYYRR', '.RYYWYYR', '..RYYYR.'];
      return this.px(frame ? f2 : f1, { R: COL.fire2, Y: COL.fire1, W: COL.white });
    });
  },

  // mini ship for map (18x12)
  miniShip(color) {
    return this.cached('mini|' + color, () => {
      const g = [
        '....F.............',
        '....MS......MS....',
        '....MSS.....MSS...',
        '....MSSS....MSSS..',
        '....MSSSS...MSSSS.',
        '....M.......M.....',
        '....M.......M.....',
        'HHHHHHHHHHHHHHHHH.',
        '.HHHHHHHHHHHHHHH..',
        '..HHHHHHHHHHHHH...',
        '...HHHHHHHHHHH....',
        '..................'];
      return this.px(g, { M: COL.wooddk, S: color, H: COL.wood, F: COL.red });
    });
  },

  // ============ SHIP EXTERIOR PAINTER ============
  // opts: {rw, rh (interior px), style, masts, sailPct, hullPct, big}
  // returns canvas; interior block is at (MX, MY) within canvas
  SHIP_MX: 30, SHIP_MY: 96,

  // small faction emblems painted on the main sail
  emblemGrid(style) {
    const G = {
      merfolk: ['..X.X.X..', '..X.X.X..', '..XXXXX..', '....X....', '....X....', '....X....', '....X....'],
      djinn: ['....X....', '...XX....', '...XXX...', '..XXXX...', '.XXXXXX..', '.XXWWXX..', '..XWWX...', '...XX....'],
      stormelf: ['....XX...', '...XX....', '..XXXX...', '....XX...', '...XX....', '..XX.....'],
      dwarf: ['.XXXXXX..', '.XXXXXX..', '....X....', '....X....', '....X....', '....X....'],
      siren: ['...XXX...', '...X.X...', '...X.....', '...X.....', '.XXX.....', '.XXX.....'],
      lizard: ['..XXXXX..', '.X..X..X.', 'X...X...X', '.X..X..X.', '..XXXXX..'],
      boss: ['....X....', '...XXX...', '..XXXXX..', '.XXXXXXX.', '..XXXXX..', '...XXX...', '....X....'],
      ghost: ['....X....', '...XXX...', '..XXXXX..', '.XXXXXXX.', '..XXXXX..', '...XXX...', '....X....'],
      human: ['....X....', '...XXX...', '....X....', '.X..X..X.', '.X..X..X.', '..XXXXX..'],
    };
    return G[style] || null;
  },
  drawEmblem(c, style, ex, ey, col) {
    if (style === 'pirate' || style === 'armada') { c.drawImage(this.icon('skull'), ex - 5, ey - 4); return; }
    const g = this.emblemGrid(style);
    if (!g) return;
    c.fillStyle = col;
    for (let y = 0; y < g.length; y++) for (let x = 0; x < g[y].length; x++) {
      if (g[y][x] === 'X') c.fillRect(ex - 4 + x, ey - 3 + y, 1, 1);
      if (g[y][x] === 'W') { c.fillStyle = COL.white; c.fillRect(ex - 4 + x, ey - 3 + y, 1, 1); c.fillStyle = col; }
    }
  },
  shipPalette(style) {
    const P = {
      human:    { hull: COL.wood, hulldk: COL.wooddk, wale: COL.gold, sail: COL.sail, accent: '#27406e', flag: '#27406e' },
      pirate:   { hull: '#5e4630', hulldk: '#3a2c1e', wale: COL.dkred, sail: '#b0a890', accent: COL.dkred, flag: COL.black },
      armada:   { hull: '#3a3a4a', hulldk: '#22222e', wale: COL.gold, sail: '#d8d0c0', accent: COL.dkred, flag: COL.dkred },
      merfolk:  { hull: COL.teal, hulldk: '#1d5f5a', wale: COL.cyan, sail: '#bfe8e4', accent: COL.blue, flag: COL.cyan },
      djinn:    { hull: '#4a2c20', hulldk: '#2e1a12', wale: COL.fire2, sail: '#e8c088', accent: COL.fire1, flag: COL.orange },
      stormelf: { hull: '#6c7d9b', hulldk: '#46546e', wale: COL.white, sail: '#dfe8f4', accent: COL.ltblue, flag: COL.ltblue },
      dwarf:    { hull: '#5a5f70', hulldk: '#3a3e4c', wale: COL.orange, sail: '#c8c0b0', accent: COL.golddk, flag: COL.orange },
      siren:    { hull: '#5c3a72', hulldk: '#3a2450', wale: COL.pink, sail: '#ecd0e0', accent: COL.pink, flag: COL.pink },
      lizard:   { hull: '#4a6038', hulldk: '#2e3e22', wale: COL.lime, sail: '#c8d0a0', accent: COL.green, flag: COL.green },
      boss:     { hull: '#7da8a4', hulldk: '#4c7572', wale: COL.mythril, sail: '#cfeeea', accent: COL.gold, flag: COL.gold },
      ghost:    { hull: '#46546e', hulldk: '#2a3344', wale: COL.cyan, sail: '#9fb2c8', accent: COL.cyan, flag: COL.cyan },
    };
    return P[style] || P.human;
  },

  shipExterior(o) {
    const key = 'shipv2|' + [o.style, o.rw, o.rh, o.masts, Math.round((o.sailPct || 1) * 4), Math.round((o.hullPct === undefined ? 1 : o.hullPct) * 5), o.big ? 1 : 0].join('|');
    return this.cached(key, () => {
      const MX = this.SHIP_MX, MY = this.SHIP_MY;
      const W = o.rw + MX + 48, H = o.rh + MY + 20;
      const cv = document.createElement('canvas');
      cv.width = W; cv.height = H;
      const c = cv.getContext('2d');
      const pal = this.shipPalette(o.style);
      const hullLt = this.shade(pal.hull, 1.25);
      const hullDk2 = this.shade(pal.hulldk, 0.7);
      const deckY = MY, keelY = MY + o.rh, bowX = MX + o.rw;

      const lantern = (lx, ly) => {
        const g = c.createRadialGradient(lx + 2, ly + 3, 1, lx + 2, ly + 3, 9);
        g.addColorStop(0, 'rgba(248,216,80,0.30)'); g.addColorStop(1, 'rgba(248,216,80,0)');
        c.fillStyle = g; c.fillRect(lx - 7, ly - 6, 18, 18);
        c.fillStyle = '#2a2a3a'; c.fillRect(lx, ly, 4, 6);
        c.fillStyle = COL.gold; c.fillRect(lx + 1, ly + 1, 2, 4);
        c.fillStyle = COL.white; c.fillRect(lx + 1, ly + 2, 1, 1);
        c.fillStyle = '#2a2a3a'; c.fillRect(lx + 1, ly - 1, 2, 1);
      };

      // ---- lower hull: stepped, curved, planked ----
      const bands = [
        { y: keelY, h: 6, inset: -18, col: pal.hull },
        { y: keelY + 6, h: 4, inset: -12, col: pal.hulldk },
        { y: keelY + 10, h: 3, inset: -5, col: hullDk2 },
        { y: keelY + 13, h: 2, inset: 2, col: '#1c1620' },
      ];
      for (const b of bands) {
        c.fillStyle = b.col;
        c.fillRect(MX + b.inset, b.y, o.rw - b.inset * 2 + 18, b.h);
        // plank seams + nails
        c.fillStyle = 'rgba(20,14,10,0.45)';
        c.fillRect(MX + b.inset, b.y, o.rw - b.inset * 2 + 18, 1);
        for (let x = MX + b.inset + ((b.y * 7) % 9); x < MX + o.rw - b.inset + 14; x += 11) {
          c.fillRect(x, b.y + 1, 1, b.h - 1);
          c.fillStyle = 'rgba(0,0,0,0.3)'; c.fillRect(x + 4, b.y + Math.max(1, b.h - 2), 1, 1);
          c.fillStyle = 'rgba(20,14,10,0.45)';
        }
      }
      // gilded wale at the waterline
      c.fillStyle = pal.wale; c.fillRect(MX - 18, keelY - 1, o.rw + 36 + 16, 1);
      c.fillStyle = 'rgba(255,255,255,0.25)'; c.fillRect(MX - 18, keelY - 1, o.rw + 30, 1);
      c.fillStyle = hullDk2; c.fillRect(MX - 18, keelY + 0, o.rw + 36 + 14, 1);
      // barnacles / moss under waterline
      c.fillStyle = o.style === 'merfolk' ? COL.cyan : '#5a6a4c';
      for (let x = MX - 8; x < bowX + 8; x += 13) c.fillRect(x + (x % 7), keelY + 8 + (x % 3), 2, 1);

      // ---- stern castle (left), tiered with golden windows ----
      const sternW = o.big ? 22 : 17;
      c.fillStyle = pal.hull;
      c.fillRect(MX - sternW, deckY - 6, sternW, o.rh + 12);
      c.fillStyle = hullLt;
      c.fillRect(MX - sternW, deckY - 6, 3, o.rh + 12);
      // plank shading on stern
      c.fillStyle = 'rgba(20,14,10,0.3)';
      for (let y = deckY - 2; y < keelY + 4; y += 5) c.fillRect(MX - sternW, y, sternW, 1);
      // raised quarterdeck cabin
      c.fillStyle = pal.hull; c.fillRect(MX - sternW - 4, deckY - 18, sternW + 6, 13);
      c.fillStyle = hullLt; c.fillRect(MX - sternW - 4, deckY - 18, sternW + 6, 2);
      c.fillStyle = pal.wale; c.fillRect(MX - sternW - 5, deckY - 20, sternW + 8, 2);
      c.fillStyle = this.shade(pal.wale, 0.65); c.fillRect(MX - sternW - 5, deckY - 19, sternW + 8, 1);
      // gold scrollwork trim down the stern
      c.fillStyle = pal.wale;
      c.fillRect(MX - 3, deckY - 18, 1, o.rh + 20);
      c.fillRect(MX - sternW, deckY - 7, sternW, 1);
      // cabin windows (warm glow) on quarterdeck + each deck
      const winRow = (wy, n) => {
        for (let i = 0; i < n; i++) {
          const wx = MX - sternW + 3 + i * 7;
          const g = c.createRadialGradient(wx + 2, wy + 3, 1, wx + 2, wy + 3, 7);
          g.addColorStop(0, 'rgba(248,216,80,0.25)'); g.addColorStop(1, 'rgba(248,216,80,0)');
          c.fillStyle = g; c.fillRect(wx - 5, wy - 4, 14, 14);
          c.fillStyle = '#3a2a16'; c.fillRect(wx - 1, wy - 1, 6, 8);
          c.fillStyle = COL.gold; c.fillRect(wx, wy, 4, 6);
          c.fillStyle = '#ffe9a8'; c.fillRect(wx, wy, 4, 2);
          c.fillStyle = '#3a2a16'; c.fillRect(wx + 1, wy, 1, 6); c.fillRect(wx, wy + 3, 4, 1);
        }
      };
      winRow(deckY - 15, Math.max(2, Math.floor(sternW / 8)));
      for (let d = 0; d < Math.floor(o.rh / 16); d++) winRow(deckY + 5 + d * 16, Math.max(1, Math.floor((sternW - 4) / 8)));
      // great stern lantern
      lantern(MX - sternW + 1, deckY - 27);
      c.fillStyle = '#2a2a3a'; c.fillRect(MX - sternW + 2, deckY - 21, 1, 3);

      // ---- bow (right): raked prow, gold beak, figurehead ----
      for (let i = 0; i < o.rh + 12; i += 2) {
        const t = i / (o.rh + 12);
        const w = Math.round(26 - 22 * t);
        c.fillStyle = t < 0.15 ? hullLt : pal.hull;
        c.fillRect(bowX, deckY - 6 + i, w, 2);
      }
      c.fillStyle = 'rgba(20,14,10,0.3)';
      for (let y = deckY - 2; y < keelY; y += 5) c.fillRect(bowX, y, Math.round(24 - 20 * ((y - deckY) / (o.rh + 10))), 1);
      // gold beak rail
      c.fillStyle = pal.wale;
      c.fillRect(bowX, deckY - 7, 24, 1);
      c.fillRect(bowX + 18, deckY - 6, 6, 1);
      // figurehead: gilded beast curling off the prow
      c.fillStyle = COL.gold;
      c.fillRect(bowX + 22, deckY - 12, 4, 8);
      c.fillRect(bowX + 24, deckY - 15, 4, 5);
      c.fillRect(bowX + 26, deckY - 17, 3, 3);
      c.fillStyle = COL.golddk;
      c.fillRect(bowX + 22, deckY - 6, 3, 3);
      c.fillRect(bowX + 25, deckY - 13, 1, 4);
      c.fillStyle = COL.white; c.fillRect(bowX + 27, deckY - 16, 1, 1);
      // bowsprit + gammoning
      c.strokeStyle = pal.hulldk; c.lineWidth = 2;
      c.beginPath(); c.moveTo(bowX + 8, deckY - 6); c.lineTo(bowX + 44, deckY - 32); c.stroke();
      c.lineWidth = 1;
      c.strokeStyle = 'rgba(40,30,20,0.7)';
      c.beginPath(); c.moveTo(bowX + 26, deckY - 19); c.lineTo(bowX + 24, deckY - 8); c.stroke();
      // jib sail
      if ((o.sailPct === undefined ? 1 : o.sailPct) > 0.05) {
        c.fillStyle = pal.sail;
        c.beginPath();
        c.moveTo(bowX + 40, deckY - 29);
        c.quadraticCurveTo(bowX + 30, deckY - 16, bowX + 14, deckY - 7);
        c.lineTo(bowX + 24, deckY - 20);
        c.closePath(); c.fill();
        c.fillStyle = COL.saildk;
        c.beginPath(); c.moveTo(bowX + 38, deckY - 28); c.lineTo(bowX + 17, deckY - 8); c.lineTo(bowX + 19, deckY - 8); c.lineTo(bowX + 38, deckY - 27); c.fill();
      }

      // ---- deck edge, railing with balusters, deck lanterns ----
      c.fillStyle = this.shade(pal.deck || COL.deck, 1);
      c.fillRect(MX, deckY - 3, o.rw, 3);
      c.fillStyle = 'rgba(20,14,10,0.35)';
      for (let x = MX + 3; x < bowX; x += 9) c.fillRect(x, deckY - 3, 1, 3);
      c.fillStyle = pal.hulldk;
      c.fillRect(MX, deckY - 9, o.rw, 2);
      for (let x = MX + 2; x < bowX - 1; x += 6) c.fillRect(x, deckY - 7, 1, 4);
      c.fillStyle = pal.wale;
      for (let x = MX + 2; x < bowX - 1; x += 24) c.fillRect(x - 1, deckY - 10, 3, 1);
      lantern(MX + Math.round(o.rw * 0.18), deckY - 16);
      lantern(MX + Math.round(o.rw * 0.82), deckY - 16);

      // ---- masts, fighting tops, sails, pennants ----
      const nm = o.masts || 2;
      const sailPct = o.sailPct === undefined ? 1 : o.sailPct;
      const mastXs = [];
      for (let m = 0; m < nm; m++) {
        const mx = MX + Math.round(o.rw * (nm === 1 ? 0.52 : 0.2 + 0.55 * m / (nm - 1) + 0.05));
        mastXs.push(mx);
        const mastTop = deckY - (o.big ? 88 : 76) + m * 6;
        // shrouds + ratlines behind mast
        c.strokeStyle = 'rgba(30,24,34,0.5)';
        c.beginPath();
        for (const side of [-1, 1]) {
          c.moveTo(mx + 1, mastTop + 26);
          c.lineTo(mx + 1 + side * 13, deckY - 8);
          c.moveTo(mx + 1, mastTop + 30);
          c.lineTo(mx + 1 + side * 9, deckY - 8);
        }
        for (let r = 0; r < 4; r++) {
          const ry = deckY - 12 - r * 9;
          const t2 = (deckY - 8 - ry) / (deckY - 8 - (mastTop + 26));
          const half = Math.round(13 * (1 - t2) + 1);
          c.moveTo(mx + 1 - half, ry); c.lineTo(mx + 1 + half, ry);
        }
        c.stroke();
        // mast: tapered, banded
        c.fillStyle = COL.wooddk; c.fillRect(mx, mastTop, 3, deckY - mastTop);
        c.fillStyle = this.shade(COL.wooddk, 1.35); c.fillRect(mx, mastTop, 1, deckY - mastTop);
        c.fillStyle = '#1c1620';
        c.fillRect(mx - 1, mastTop + 24, 5, 2); c.fillRect(mx - 1, mastTop + 50, 5, 2);
        // fighting top platform
        c.fillStyle = pal.hulldk; c.fillRect(mx - 4, mastTop + 21, 11, 3);
        c.fillStyle = hullLt; c.fillRect(mx - 4, mastTop + 21, 11, 1);
        // crow's nest barrel on tallest mast
        if (m === 0) {
          c.fillStyle = pal.hull; c.fillRect(mx - 3, mastTop + 14, 9, 7);
          c.fillStyle = hullDk2; c.fillRect(mx - 3, mastTop + 14, 9, 1); c.fillRect(mx - 3, mastTop + 20, 9, 1);
        }
        // yards + billowed sails
        const yw = (o.big ? 50 : 38) - m * 4;
        for (let s = 0; s < 2; s++) {
          const yy = mastTop + 6 + s * 30;
          const yw2 = yw - s * 6;
          c.fillStyle = COL.wooddk; c.fillRect(mx - yw2 / 2 + 1, yy, yw2 + 1, 2);
          c.fillStyle = this.shade(COL.wooddk, 1.35); c.fillRect(mx - yw2 / 2 + 1, yy, yw2 + 1, 1);
          if (sailPct > 0.05) {
            const sh = Math.round(24 * sailPct);
            const lx = mx - yw2 / 2 + 2, rx = mx + yw2 / 2 + 1;
            c.fillStyle = pal.sail;
            c.beginPath();
            c.moveTo(lx, yy + 2);
            c.lineTo(rx, yy + 2);
            c.quadraticCurveTo(rx + 5, yy + 2 + sh * 0.6, rx - 4, yy + 2 + sh);
            c.quadraticCurveTo(mx, yy + sh + 7, lx + 4, yy + 2 + sh);
            c.quadraticCurveTo(lx - 5, yy + 2 + sh * 0.6, lx, yy + 2);
            c.closePath(); c.fill();
            // seams
            c.strokeStyle = 'rgba(120,108,84,0.55)';
            for (let q = 1; q <= 3; q++) {
              c.beginPath();
              c.moveTo(lx - 2 + q, yy + 2 + sh * q / 4);
              c.quadraticCurveTo(mx, yy + 5 + sh * q / 4, rx + 2 - q, yy + 2 + sh * q / 4);
              c.stroke();
            }
            // shading: port side dark, starboard highlight
            c.fillStyle = 'rgba(60,50,40,0.18)';
            c.beginPath();
            c.moveTo(lx, yy + 2); c.quadraticCurveTo(lx - 5, yy + 2 + sh * 0.6, lx + 4, yy + 2 + sh);
            c.lineTo(lx + 9, yy + 2 + sh); c.lineTo(lx + 6, yy + 2); c.closePath(); c.fill();
            c.fillStyle = 'rgba(255,255,255,0.22)';
            c.fillRect(rx - 9, yy + 4, 2, sh - 4);
          }
        }
        // faction emblem on the main course sail
        if (m === Math.floor((nm - 1) / 2) && sailPct > 0.5) {
          this.drawEmblem(c, o.style, mx + 1, mastTop + 17 + 36, pal.accent);
        }
        // masthead: gold truck + swallow-tail pennant
        c.fillStyle = COL.gold; c.fillRect(mx, mastTop - 2, 3, 2);
        c.fillStyle = pal.flag;
        c.beginPath();
        c.moveTo(mx + 3, mastTop - 8);
        c.lineTo(mx + 19, mastTop - 6);
        c.lineTo(mx + 14, mastTop - 4);
        c.lineTo(mx + 19, mastTop - 2);
        c.lineTo(mx + 3, mastTop - 1);
        c.closePath(); c.fill();
        c.fillStyle = 'rgba(0,0,0,0.25)'; c.fillRect(mx + 3, mastTop - 4, 12, 1);
      }
      // stays: masthead to bowsprit & stern
      c.strokeStyle = 'rgba(30,24,34,0.55)';
      c.beginPath();
      c.moveTo(mastXs[0] + 1, deckY - (o.big ? 88 : 76) + 2);
      c.lineTo(bowX + 42, deckY - 31);
      c.moveTo(mastXs[nm - 1] + 1, deckY - (o.big ? 88 : 76) + (nm - 1) * 6 + 2);
      c.lineTo(MX - sternW + 2, deckY - 18);
      if (nm > 1) { c.moveTo(mastXs[0] + 1, deckY - (o.big ? 88 : 76) + 6); c.lineTo(mastXs[nm - 1] + 1, deckY - (o.big ? 88 : 76) + (nm - 1) * 6 + 8); }
      c.stroke();

      // ---- style flourishes ----
      if (o.style === 'dwarf') {
        c.fillStyle = COL.grey;
        for (let x = MX - 12; x < bowX + 10; x += 9) { c.fillRect(x, keelY + 2, 2, 2); c.fillRect(x + 4, keelY + 7, 1, 1); }
        c.fillStyle = COL.orange; c.fillRect(MX - 10, deckY - 12, 2, 2);
      }
      if (o.style === 'merfolk') {
        c.fillStyle = COL.cyan;
        for (let x = MX - 10; x < bowX + 6; x += 14) { c.fillRect(x, keelY + 3, 6, 2); c.fillRect(x + 2, keelY + 5, 2, 1); }
        c.fillStyle = 'rgba(127,212,210,0.4)'; c.fillRect(MX - 6, deckY - 5, o.rw, 1);
      }
      if (o.style === 'djinn') {
        c.fillStyle = COL.fire1;
        for (let x = MX - 12; x < bowX + 12; x += 6) c.fillRect(x, keelY + 4, 3, 1);
        const g = c.createRadialGradient(bowX + 24, deckY - 12, 1, bowX + 24, deckY - 12, 10);
        g.addColorStop(0, 'rgba(240,128,32,0.5)'); g.addColorStop(1, 'rgba(240,128,32,0)');
        c.fillStyle = g; c.fillRect(bowX + 12, deckY - 24, 26, 26);
      }
      if (o.style === 'boss') {
        c.fillStyle = COL.mythril;
        for (let x = MX - 14; x < bowX + 14; x += 8) c.fillRect(x, keelY - 3, 4, 1);
        c.fillStyle = COL.white;
        c.fillRect(MX + 6, keelY + 2, 2, 2); c.fillRect(MX + o.rw - 12, keelY + 3, 2, 2);
        c.fillRect(MX + o.rw * 0.5, deckY - 8, 2, 2);
      }
      if (o.style === 'ghost') {
        c.fillStyle = 'rgba(127,212,210,0.25)';
        c.fillRect(MX - sternW, deckY - 20, o.rw + sternW + 26, o.rh + 30);
      }

      // ---- battle damage ----
      const hp = o.hullPct === undefined ? 1 : o.hullPct;
      if (hp < 0.65) {
        c.fillStyle = '#1c1620';
        c.fillRect(MX - 8, keelY + 2, 5, 2); c.fillRect(bowX + 4, keelY - 4, 2, 5);
        c.fillRect(MX + Math.round(o.rw * 0.4), keelY + 5, 6, 2);
        c.fillStyle = 'rgba(60,60,70,0.6)';
        c.fillRect(MX + Math.round(o.rw * 0.3), deckY - 26, 3, 3);
      }
      if (hp < 0.35) {
        c.fillStyle = '#1c1620';
        c.fillRect(MX - 14, deckY + 8, 4, 6); c.fillRect(bowX + 2, keelY + 1, 6, 3);
        c.fillRect(MX + Math.round(o.rw * 0.7), keelY + 6, 7, 3);
      }
      return cv;
    });
  },

  // lighten/darken a hex color
  shade(hex, f) {
    const n = parseInt(hex.slice(1), 16);
    const r = U.clamp(Math.round(((n >> 16) & 255) * f), 0, 255);
    const g = U.clamp(Math.round(((n >> 8) & 255) * f), 0, 255);
    const b = U.clamp(Math.round((n & 255) * f), 0, 255);
    return 'rgb(' + r + ',' + g + ',' + b + ')';
  },

  // ============ FURNISHED INTERIOR PAINTER ============
  // static cutaway interior for a ship layout: planked walls, furniture, lanterns, doors, ladders
  shipInterior(layoutKey, style) {
    const key = 'interior|' + layoutKey + '|' + style;
    return this.cached(key, () => {
      const L = DATA.LAYOUTS[layoutKey];
      const T = 16;
      const rw = Math.max(...L.rooms.map(r => r[1] + r[3])) * T;
      const rh = Math.max(...L.rooms.map(r => r[2] + r[4])) * T;
      const cv = document.createElement('canvas');
      cv.width = rw; cv.height = rh;
      const c = cv.getContext('2d');

      const lanternGlow = (lx, ly, str) => {
        const g = c.createRadialGradient(lx, ly, 1, lx, ly, 12);
        g.addColorStop(0, 'rgba(248,216,80,' + (str || 0.16) + ')');
        g.addColorStop(1, 'rgba(248,216,80,0)');
        c.fillStyle = g; c.fillRect(lx - 12, ly - 12, 24, 24);
      };

      for (const [keyName, gx, gy, gw, gh] of L.rooms) {
        const x = gx * T, y = gy * T, w = gw * T, h = gh * T;
        const dim = 1 - gy * 0.09; // lower decks darker
        // back wall: vertical planks
        c.fillStyle = this.shade('#9a7848', dim);
        c.fillRect(x, y, w, h);
        c.fillStyle = 'rgba(70,48,28,0.35)';
        for (let px2 = x + 4; px2 < x + w; px2 += 5) c.fillRect(px2, y, 1, h);
        // ceiling beam + floor
        c.fillStyle = this.shade('#5e3a22', dim); c.fillRect(x, y, w, 2);
        c.fillStyle = this.shade('#6e4c2c', dim); c.fillRect(x, y + h - 3, w, 3);
        c.fillStyle = 'rgba(40,26,14,0.5)';
        for (let px2 = x + 5; px2 < x + w; px2 += 8) c.fillRect(px2, y + h - 3, 1, 3);
        c.fillStyle = 'rgba(255,235,180,0.07)'; c.fillRect(x + 1, y + 2, w - 2, 2);

        // furniture by system (left/right edges; crew stand mid)
        const fy = y + h - 3; // floor line
        switch (keyName) {
          case 'helm': {
            // ship's wheel
            c.fillStyle = COL.golddk;
            c.fillRect(x + w - 12, y + 4, 8, 8);
            c.fillStyle = this.shade('#9a7848', dim); c.fillRect(x + w - 10, y + 6, 4, 4);
            c.fillStyle = COL.gold;
            c.fillRect(x + w - 9, y + 3, 2, 10); c.fillRect(x + w - 13, y + 7, 10, 2);
            c.fillStyle = COL.wooddk; c.fillRect(x + w - 9, fy - 2, 2, 2);
            // chart table
            c.fillStyle = COL.wooddk; c.fillRect(x + 2, fy - 5, 9, 1); c.fillRect(x + 3, fy - 4, 1, 4); c.fillRect(x + 9, fy - 4, 1, 4);
            c.fillStyle = '#d8c498'; c.fillRect(x + 3, fy - 7, 7, 2);
            c.fillStyle = COL.red; c.fillRect(x + 6, fy - 7, 1, 1);
            break;
          }
          case 'infirmary': {
            // cot with red blanket
            c.fillStyle = COL.wooddk; c.fillRect(x + 2, fy - 4, 12, 1); c.fillRect(x + 2, fy - 3, 1, 3); c.fillRect(x + 13, fy - 3, 1, 3);
            c.fillStyle = COL.red; c.fillRect(x + 3, fy - 6, 9, 2);
            c.fillStyle = COL.white; c.fillRect(x + 11, fy - 7, 3, 3);
            // medicine shelf
            c.fillStyle = COL.wooddk; c.fillRect(x + w - 13, y + 5, 11, 1);
            const cols = [COL.lime, COL.cyan, COL.pink, COL.gold];
            for (let i = 0; i < 4; i++) { c.fillStyle = cols[i]; c.fillRect(x + w - 12 + i * 3, y + 2, 2, 3); }
            break;
          }
          case 'sails': {
            // rope coil
            c.fillStyle = '#b89868'; c.fillRect(x + 3, fy - 4, 7, 4);
            c.fillStyle = '#8a6a40'; c.fillRect(x + 4, fy - 3, 5, 1); c.fillRect(x + 5, fy - 1, 3, 1);
            // winch
            c.fillStyle = COL.wooddk; c.fillRect(x + w - 10, fy - 6, 2, 6); c.fillRect(x + w - 12, fy - 7, 6, 2);
            c.fillStyle = COL.golddk; c.fillRect(x + w - 11, fy - 6, 4, 3);
            break;
          }
          case 'weapons': {
            // powder kegs
            c.fillStyle = '#7a5230'; c.fillRect(x + 2, fy - 7, 6, 7); c.fillRect(x + 9, fy - 5, 5, 5);
            c.fillStyle = '#3a2a16'; c.fillRect(x + 2, fy - 5, 6, 1); c.fillRect(x + 2, fy - 3, 6, 1); c.fillRect(x + 9, fy - 4, 5, 1);
            // cannonball pyramid
            c.fillStyle = '#2a2a3a';
            c.fillRect(x + w - 12, fy - 2, 2, 2); c.fillRect(x + w - 9, fy - 2, 2, 2); c.fillRect(x + w - 6, fy - 2, 2, 2);
            c.fillRect(x + w - 10, fy - 4, 2, 2); c.fillRect(x + w - 7, fy - 4, 2, 2);
            c.fillRect(x + w - 9, fy - 6, 2, 2);
            break;
          }
          case 'core': {
            // mana crystal on pedestal, glowing
            const cx2 = x + w - 11;
            const g = c.createRadialGradient(cx2 + 3, y + 9, 1, cx2 + 3, y + 9, 13);
            g.addColorStop(0, 'rgba(127,212,210,0.4)'); g.addColorStop(1, 'rgba(127,212,210,0)');
            c.fillStyle = g; c.fillRect(cx2 - 10, y - 4, 26, 26);
            c.fillStyle = COL.dkgrey; c.fillRect(cx2, fy - 3, 7, 3); c.fillRect(cx2 + 1, fy - 4, 5, 1);
            c.fillStyle = COL.teal;
            c.fillRect(cx2 + 2, y + 5, 3, 9);
            c.fillStyle = COL.cyan;
            c.fillRect(cx2 + 1, y + 7, 5, 5); c.fillRect(cx2 + 2, y + 4, 3, 3);
            c.fillStyle = COL.white; c.fillRect(cx2 + 2, y + 6, 1, 3);
            // rune marks on wall
            c.fillStyle = 'rgba(127,212,210,0.5)';
            c.fillRect(x + 3, y + 4, 1, 3); c.fillRect(x + 6, y + 5, 2, 1); c.fillRect(x + 10, y + 4, 1, 3);
            break;
          }
          case 'wards': {
            // shield on wall + candles
            c.fillStyle = COL.dkblue; c.fillRect(x + w - 12, y + 3, 8, 9);
            c.fillStyle = COL.cyan; c.fillRect(x + w - 11, y + 4, 6, 6); c.fillRect(x + w - 10, y + 10, 4, 1);
            c.fillStyle = COL.white; c.fillRect(x + w - 10, y + 5, 1, 2);
            c.fillStyle = COL.sail; c.fillRect(x + 3, fy - 4, 1, 4); c.fillRect(x + 6, fy - 3, 1, 3);
            c.fillStyle = COL.fire1; c.fillRect(x + 3, fy - 5, 1, 1); c.fillRect(x + 6, fy - 4, 1, 1);
            lanternGlow(x + 4, fy - 5, 0.1);
            break;
          }
          case 'brinegate': {
            // stone portal ring with watery shimmer
            const px3 = x + w / 2, py3 = y + 9;
            const g = c.createRadialGradient(px3, py3, 1, px3, py3, 12);
            g.addColorStop(0, 'rgba(124,76,160,0.45)'); g.addColorStop(1, 'rgba(124,76,160,0)');
            c.fillStyle = g; c.fillRect(px3 - 12, py3 - 12, 24, 24);
            c.strokeStyle = COL.purple; c.lineWidth = 2;
            c.beginPath(); c.arc(px3, py3, 6, 0, Math.PI * 2); c.stroke();
            c.lineWidth = 1;
            c.strokeStyle = COL.cyan;
            c.beginPath(); c.arc(px3, py3, 3, 0.5, Math.PI * 1.6); c.stroke();
            c.fillStyle = COL.grey; c.fillRect(px3 - 7, fy - 2, 14, 2);
            break;
          }
          case 'fogveil': {
            // censer with rising smoke
            c.fillStyle = COL.dkgrey; c.fillRect(x + w - 10, fy - 5, 6, 4); c.fillRect(x + w - 9, fy - 6, 4, 1);
            c.fillStyle = COL.gold; c.fillRect(x + w - 9, fy - 4, 4, 1);
            c.fillStyle = 'rgba(197,202,214,0.5)';
            c.fillRect(x + w - 8, y + 8, 2, 2); c.fillRect(x + w - 10, y + 5, 2, 2); c.fillRect(x + w - 7, y + 3, 2, 2);
            break;
          }
          case 'lookout': {
            // spyglass on tripod + rolled charts
            c.strokeStyle = COL.golddk;
            c.beginPath(); c.moveTo(x + w - 11, fy - 7); c.lineTo(x + w - 4, y + 5); c.stroke();
            c.fillStyle = COL.gold; c.fillRect(x + w - 6, y + 4, 3, 2);
            c.fillStyle = COL.wooddk; c.fillRect(x + w - 12, fy - 3, 1, 3); c.fillRect(x + w - 9, fy - 3, 1, 3);
            c.fillStyle = '#d8c498'; c.fillRect(x + 3, fy - 3, 6, 1); c.fillRect(x + 4, fy - 4, 6, 1);
            break;
          }
          case 'doors': {
            // lockers
            c.fillStyle = COL.wooddk; c.fillRect(x + 2, y + 4, 5, h - 7); c.fillRect(x + 8, y + 4, 5, h - 7);
            c.fillStyle = this.shade('#9a7848', dim * 1.1); c.fillRect(x + 3, y + 5, 3, h - 9); c.fillRect(x + 9, y + 5, 3, h - 9);
            c.fillStyle = COL.gold; c.fillRect(x + 5, y + 8, 1, 1); c.fillRect(x + 11, y + 8, 1, 1);
            break;
          }
          default: {
            // hold: barrels, crate, sack
            c.fillStyle = '#7a5230'; c.fillRect(x + 3, fy - 7, 6, 7);
            c.fillStyle = '#3a2a16'; c.fillRect(x + 3, fy - 5, 6, 1); c.fillRect(x + 3, fy - 3, 6, 1);
            c.fillStyle = COL.wood; c.fillRect(x + w - 12, fy - 6, 8, 6);
            c.fillStyle = COL.wooddk; c.fillRect(x + w - 12, fy - 6, 8, 1); c.fillRect(x + w - 9, fy - 6, 1, 6);
            c.fillStyle = '#c8b070'; c.fillRect(x + 11, fy - 4, 4, 4); c.fillRect(x + 12, fy - 5, 2, 1);
            break;
          }
        }
        // hanging lantern in every room
        const lx = x + Math.round(w * 0.5) - 6, ly = y + 3;
        lanternGlow(lx + 1, ly + 2, 0.13);
        c.fillStyle = '#2a2a3a'; c.fillRect(lx, ly, 3, 4); c.fillRect(lx + 1, ly - 2, 1, 2);
        c.fillStyle = COL.gold; c.fillRect(lx + 1, ly + 1, 1, 2);
      }

      // doorways & ladders between rooms
      for (const [a, b] of L.doors) {
        const A = L.rooms[a], B = L.rooms[b];
        if (A[2] === B[2]) {
          // horizontal neighbors: doorway in shared wall
          const bx = Math.max(A[1], B[1]) === B[1] ? B[1] * T : A[1] * T;
          const yy = A[2] * T;
          c.fillStyle = '#241a10';
          c.fillRect(bx - 2, yy + 4, 4, T - 7);
          c.fillStyle = COL.wooddk; c.fillRect(bx - 3, yy + 3, 6, 1);
        } else {
          // vertical: ladder through the deck
          const top = A[2] < B[2] ? A : B, bot = A[2] < B[2] ? B : A;
          const ox = Math.max(top[1], bot[1]), ow = Math.min(top[1] + top[3], bot[1] + bot[3]) - ox;
          const lx2 = (ox + ow / 2) * T - 3;
          const ly2 = bot[2] * T - 4;
          c.fillStyle = '#241a10'; c.fillRect(lx2 - 1, ly2, 8, 5);
          c.fillStyle = COL.wooddk; c.fillRect(lx2, ly2 - 1, 1, 14); c.fillRect(lx2 + 5, ly2 - 1, 1, 14);
          c.fillStyle = COL.woodlt;
          for (let r = 0; r < 4; r++) c.fillRect(lx2 + 1, ly2 + 1 + r * 3, 4, 1);
        }
      }
      // hull cutaway frame: ribs between decks
      c.fillStyle = 'rgba(40,26,14,0.55)';
      for (let d = 1; d < rh / T; d++) c.fillRect(0, d * T - 1, rw, 2);
      return cv;
    });
  },

  // ============ EVENT VIGNETTES (96x54 scenes) ============
  vignette(name) {
    return this.cached('vig|' + name, () => {
      const W = 96, H = 54;
      const cv = document.createElement('canvas');
      cv.width = W; cv.height = H;
      const c = cv.getContext('2d');
      const horizon = 34;
      // sky bands
      const skyCols = name === 'storm' || name === 'kraken' ? ['#2a2a3e', '#3a3a52', '#494f63']
        : name === 'fog' ? ['#6c7888', '#8c93a6', '#a8aebc']
        : name === 'city' || name === 'boss' ? ['#2a3f73', '#46548e', '#6c7d9b']
        : [COL.skytop, COL.sky, COL.skyhi];
      for (let i = 0; i < 3; i++) { c.fillStyle = skyCols[i]; c.fillRect(0, i * 12, W, 12); }
      c.fillStyle = skyCols[2]; c.fillRect(0, 36 - 12 + 10, W, horizon - 34 + 0);
      // sea
      c.fillStyle = name === 'storm' || name === 'kraken' ? '#142f44' : COL.sea;
      c.fillRect(0, horizon, W, H - horizon);
      c.fillStyle = name === 'storm' || name === 'kraken' ? '#1d4458' : COL.seahi;
      for (let x = 0; x < W; x += 8) c.fillRect(x + (x % 16 ? 3 : 0), horizon + 2 + (x % 24) / 8, 5, 1);
      // helpers
      const island = (x, w, h, col, coldk) => {
        c.fillStyle = coldk; c.fillRect(x - 2, horizon - 2, w + 4, 3);
        c.fillStyle = col;
        c.beginPath(); c.moveTo(x, horizon); c.lineTo(x + w * 0.3, horizon - h);
        c.lineTo(x + w * 0.7, horizon - h * 0.8); c.lineTo(x + w, horizon); c.closePath(); c.fill();
      };
      const palm = (x, y) => {
        c.fillStyle = COL.wooddk; c.fillRect(x, y - 8, 2, 8);
        c.fillStyle = COL.green;
        c.fillRect(x - 4, y - 10, 4, 2); c.fillRect(x + 2, y - 10, 4, 2);
        c.fillRect(x - 2, y - 12, 6, 2);
      };
      const shipSil = (x, y, s, col) => {
        c.fillStyle = col;
        c.fillRect(x, y - 2 * s, 14 * s, 3 * s);
        c.fillRect(x + 3 * s, y - 9 * s, s, 7 * s);
        c.fillRect(x + 9 * s, y - 11 * s, s, 9 * s);
        c.beginPath(); c.moveTo(x + 4 * s, y - 8 * s); c.lineTo(x + 8 * s, y - 8 * s); c.lineTo(x + 7 * s, y - 3 * s); c.lineTo(x + 4 * s, y - 3 * s); c.closePath(); c.fill();
        c.beginPath(); c.moveTo(x + 10 * s, y - 10 * s); c.lineTo(x + 14 * s, y - 10 * s); c.lineTo(x + 13 * s, y - 3 * s); c.lineTo(x + 10 * s, y - 3 * s); c.closePath(); c.fill();
      };
      switch (name) {
        case 'island':
          island(20, 50, 14, '#5a7a3c', '#c8b070'); palm(40, horizon - 6); palm(52, horizon - 3); break;
        case 'volcano':
          island(24, 48, 22, '#5e3a3a', '#3a2222');
          c.fillStyle = COL.fire2; c.fillRect(36, horizon - 23, 8, 3);
          c.fillStyle = COL.fire1; c.fillRect(38, horizon - 26, 4, 3);
          c.fillStyle = '#6a6a7a'; c.fillRect(34, 2, 14, 4); c.fillRect(40, 6, 12, 3); break;
        case 'port':
          island(8, 80, 10, '#5a7a3c', '#c8b070');
          c.fillStyle = COL.wood; c.fillRect(20, horizon - 12, 8, 12); c.fillRect(36, horizon - 16, 10, 16); c.fillRect(56, horizon - 10, 8, 10);
          c.fillStyle = COL.red; c.fillRect(19, horizon - 15, 10, 3); c.fillRect(35, horizon - 19, 12, 3); c.fillRect(55, horizon - 13, 10, 3);
          c.fillStyle = COL.gold; c.fillRect(39, horizon - 12, 3, 3); c.fillRect(23, horizon - 8, 2, 2);
          c.fillStyle = COL.wooddk; c.fillRect(64, horizon, 24, 2); break;
        case 'storm':
          c.fillStyle = '#22222e'; c.fillRect(8, 2, 30, 8); c.fillRect(50, 4, 36, 9); c.fillRect(28, 8, 40, 6);
          c.fillStyle = COL.fire1; c.fillRect(44, 12, 3, 8); c.fillRect(41, 20, 3, 8); c.fillRect(45, 28, 2, 6);
          c.fillStyle = '#6c7888'; for (let i = 0; i < 26; i++) c.fillRect((i * 17) % W, 14 + (i * 11) % 22, 1, 4);
          break;
        case 'ruins':
          island(18, 56, 12, '#6a6a7a', '#494f63');
          c.fillStyle = '#8c93a6'; c.fillRect(30, horizon - 24, 5, 14); c.fillRect(42, horizon - 20, 5, 10); c.fillRect(54, horizon - 26, 5, 16);
          c.fillStyle = '#494f63'; c.fillRect(28, horizon - 26, 34, 3); break;
        case 'wreck':
          c.fillStyle = COL.wooddk;
          c.save(); c.translate(48, horizon + 6); c.rotate(-0.35);
          c.fillRect(-16, -3, 32, 6); c.fillRect(-2, -16, 2, 14); c.restore();
          c.fillStyle = COL.saildk; c.fillRect(43, horizon - 10, 8, 6); break;
        case 'jungle':
          island(12, 70, 16, '#2e5e2e', '#1f421f');
          palm(28, horizon - 10); palm(44, horizon - 14); palm(60, horizon - 8);
          c.fillStyle = COL.gold; c.fillRect(50, horizon - 20, 4, 6); break;
        case 'reef':
          c.fillStyle = '#c87898'; c.fillRect(18, horizon + 4, 8, 4); c.fillRect(40, horizon + 7, 10, 3); c.fillRect(66, horizon + 3, 7, 5);
          c.fillStyle = COL.cyan; c.fillRect(20, horizon + 2, 4, 2); c.fillRect(44, horizon + 5, 4, 2); c.fillRect(68, horizon + 1, 3, 2);
          island(70, 22, 8, '#c8b070', '#a89058'); break;
        case 'city':
          island(10, 76, 12, '#4c7572', '#2f4f4c');
          c.fillStyle = COL.mythril;
          c.fillRect(28, horizon - 30, 6, 20); c.fillRect(42, horizon - 38, 7, 28); c.fillRect(58, horizon - 28, 6, 18);
          c.fillStyle = COL.white;
          c.fillRect(30, horizon - 33, 2, 3); c.fillRect(44, horizon - 42, 3, 4); c.fillRect(60, horizon - 31, 2, 3);
          c.fillStyle = COL.gold; c.fillRect(45, horizon - 45, 1, 3); break;
        case 'armada':
          shipSil(8, horizon + 4, 1, '#22222e'); shipSil(38, horizon + 2, 1, '#2a2a3e'); shipSil(66, horizon + 5, 1, '#22222e');
          c.fillStyle = COL.dkred; c.fillRect(12, horizon - 8, 4, 2); c.fillRect(48, horizon - 10, 4, 2); c.fillRect(76, horizon - 7, 4, 2); break;
        case 'kraken': {
          c.fillStyle = '#2e4438';
          const t = (x, h2) => { for (let i = 0; i < h2; i++) c.fillRect(x + Math.round(Math.sin(i * 0.5) * 3), horizon - i, 4 - (i > h2 - 5 ? 2 : 0), 1); };
          t(20, 20); t(40, 28); t(62, 18); t(76, 24);
          c.fillStyle = '#8fd45a'; c.fillRect(42, horizon - 26, 2, 2); break;
        }
        case 'fog':
          c.fillStyle = 'rgba(200,205,215,0.7)';
          c.fillRect(0, 10, W, 8); c.fillRect(0, 24, W, 10); c.fillRect(0, 40, W, 6);
          shipSil(36, horizon + 4, 1, '#5a6478'); break;
        case 'boss':
          shipSil(26, horizon + 6, 2, '#4c7572');
          c.fillStyle = COL.mythril; c.fillRect(26, horizon + 2, 30, 2);
          c.fillStyle = COL.gold; c.fillRect(34, horizon - 24, 5, 3); c.fillRect(46, horizon - 28, 5, 3); break;
        case 'shop':
          island(20, 56, 10, '#5a7a3c', '#c8b070');
          c.fillStyle = COL.wood; c.fillRect(34, horizon - 14, 16, 14);
          c.fillStyle = COL.gold; c.fillRect(36, horizon - 18, 12, 4);
          c.fillStyle = COL.white; c.fillRect(40, horizon - 10, 4, 4);
          c.fillStyle = COL.wooddk; c.fillRect(52, horizon, 20, 2); break;
        case 'mermaid':
          c.fillStyle = '#79c4b8'; c.fillRect(40, horizon - 6, 5, 6);
          c.fillStyle = COL.teal; c.fillRect(40, horizon, 8, 3); c.fillRect(46, horizon + 2, 5, 2);
          c.fillStyle = COL.cyan; c.fillRect(38, horizon - 9, 9, 3);
          island(64, 26, 9, '#c8b070', '#a89058'); break;
        default:
          island(24, 44, 12, '#5a7a3c', '#c8b070'); palm(40, horizon - 7);
      }
      // frame
      c.fillStyle = COL.gold;
      c.fillRect(0, 0, W, 1); c.fillRect(0, H - 1, W, 1); c.fillRect(0, 0, 1, H); c.fillRect(W - 1, 0, 1, H);
      return cv;
    });
  },
};
